// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkgnUJAW5_GAb8dYOMUJ4FtVhtdr7BIX8',
    appId: '1:921463332242:web:a235a6ed49434eb440354b',
    messagingSenderId: '921463332242',
    projectId: 'tp3-iot-3443b',
    authDomain: 'tp3-iot-3443b.firebaseapp.com',
    storageBucket: 'tp3-iot-3443b.firebasestorage.app',
    measurementId: 'G-Q5F5JQVRDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCguK1VwzZXnPlN2lRxVhSdLQIW9GEejjo',
    appId: '1:921463332242:android:21944f0acd237f7440354b',
    messagingSenderId: '921463332242',
    projectId: 'tp3-iot-3443b',
    storageBucket: 'tp3-iot-3443b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDesQcD7DqNU00iotKocw5IWuZsZ5LIKGg',
    appId: '1:921463332242:ios:67e6f3e4654d7a6240354b',
    messagingSenderId: '921463332242',
    projectId: 'tp3-iot-3443b',
    storageBucket: 'tp3-iot-3443b.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDesQcD7DqNU00iotKocw5IWuZsZ5LIKGg',
    appId: '1:921463332242:ios:67e6f3e4654d7a6240354b',
    messagingSenderId: '921463332242',
    projectId: 'tp3-iot-3443b',
    storageBucket: 'tp3-iot-3443b.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkgnUJAW5_GAb8dYOMUJ4FtVhtdr7BIX8',
    appId: '1:921463332242:web:fcbe7d51e39e34e840354b',
    messagingSenderId: '921463332242',
    projectId: 'tp3-iot-3443b',
    authDomain: 'tp3-iot-3443b.firebaseapp.com',
    storageBucket: 'tp3-iot-3443b.firebasestorage.app',
    measurementId: 'G-073MM7S7F8',
  );
}
